apiVersion: apps/v1
kind: Deployment
metadata:
  name: leejingyeong-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leejingyeong
  template:
    metadata:
      labels:
        app: leejingyeong
    spec:
      containers:
      - name: backend
        image: leejingyeong/backend:latest
        ports:
        - containerPort: 8000
      - name: frontend
        image: leejingyeong/frontend:latest
        ports:
        - containerPort: 3000