apiVersion: apps/v1
kind: Deployment
metadata:
  name: leejingyeong-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leejingyeong
  template:
    metadata:
      labels:
        app: leejingyeong
    spec:
      containers:
        - name: backend
          image: leejingyeong/backend:latest
          ports:
            - containerPort: 8000
        - name: frontend
          image: leejingyeong/frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: leejingyeong-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: leejingyeong
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 31460
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: leejingyeong-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: www.test.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: leejingyeong-service
                port:
                  number: 80