apiVersion: v1
kind: Service
metadata:
  name: leejingyeong-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: leejingyeong
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 31460